// Route A constants generator for ff_math.hpp.
// Splits each Bailey DD constant (FP64 hi, FP64 lo) into an FF pair (FP32 hi, FP32 lo)
// by rounding the unevaluated sum hi64+lo64 to its nearest representable FF value.
//
// Build: g++ -std=c++17 -O2 scripts/gen_ff_constants.cpp -o scripts/gen_ff_constants
// Run:   ./scripts/gen_ff_constants
// Paste the printed block into third_party/include/ff_math.hpp (constants section).

#include <cstdio>
#include <cstdint>
#include <cstring>

struct DD { uint64_t hi_bits, lo_bits; const char* name; const char* desc; };

static const DD CONSTANTS[] = {
    {0x400921fb54442d18ULL, 0x3ca1a62633145c07ULL, "ff_pi",          "pi"},
    {0x4005bf0a8b145769ULL, 0x3ca4d57ee2b1013aULL, "ff_e",           "e"},
    {0x3fe62e42fefa39efULL, 0x3c7abc9e3b39803fULL, "ff_log2",        "ln(2)"},
    {0x40026bb1bbb55516ULL, 0xbcaf48ad494ea3eaULL, "ff_log10",       "ln(10)"},
    {0x3ff6a09e667f3bcdULL, 0xbc9bdd3413b26456ULL, "ff_sqrt2",       "sqrt(2)"},
    {0x3fe2788cfc6fb619ULL, 0xbc56cb90701fbfabULL, "ff_euler_gamma", "Euler gamma"},
};

static double bits_to_double(uint64_t bits) {
    double d; std::memcpy(&d, &bits, sizeof(double)); return d;
}
static uint32_t float_to_bits(float f) {
    uint32_t b; std::memcpy(&b, &f, sizeof(float)); return b;
}

int main() {
    std::printf("// Auto-generated by scripts/gen_ff_constants.cpp -- do not edit by hand.\n");
    std::printf("// Route A: round_to_nearest_FF(Bailey FP64 hi+lo pair).\n\n");
    for (const auto& c : CONSTANTS) {
        double hi64 = bits_to_double(c.hi_bits);
        double lo64 = bits_to_double(c.lo_bits);
        float  hi32 = (float)hi64;                              // nearest FP32 of hi64
        double residual = (hi64 - (double)hi32) + lo64;         // exact in FP64
        float  lo32 = (float)residual;                          // nearest FP32 of residual
        uint32_t hi_bits = float_to_bits(hi32);
        uint32_t lo_bits = float_to_bits(lo32);
        std::printf("KOKKOS_INLINE_FUNCTION ffloat %-15s() { return make_ff(0x%08xU, 0x%08xU); } // %s\n",
                    c.name, hi_bits, lo_bits, c.desc);
    }
    return 0;
}
